apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
    jaeger-infra: query-service
spec:
  ports:
    - name: jaeger
      port: 16686
      targetPort: 16686
    - name: zipkin
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
    jaeger-infra: agent-daemonset
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: agent-instance
          image: jaegertracing/all-in-one:1.18
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          ports:
            - containerPort: 9411
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
          resources:
            requests:
              memory: 200M
              cpu: 200m
            limits:
              memory: 200M
              cpu: 200m
