---
apiVersion: v1
kind: Service
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  selector:
    app: service-2
  ports:
    - port: 81
      targetPort: 7070
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-2
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "service-2"
        dapr.io/port: "7070"
    spec:
      containers:
        - name: service-2
          image: harshanarayana/dapr-series-service-2:latest
          ports:
            - containerPort: 7070
              name: http
