apiVersion: v1
kind: Service
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  selector:
    app: service-1
  ports:
    - port: 80
      targetPort: 6060
      name: http
  type: LoadBalancer

